import type {
  CurrencyCode,
  CurrencyInfo,
  RoleLevelId,
  RoleLevel,
  TeamDefinition,
  TeamQuestion,
  FormDataState,
} from './types';

// ── Currency definitions (7 currencies) ──
export const currencies: Record<CurrencyCode, CurrencyInfo> = {
  AED: { name: 'UAE Dirham', symbol: 'AED', flag: '\u{1F1E6}\u{1F1EA}', formatting: 'standard' },
  USD: { name: 'US Dollar', symbol: '$', flag: '\u{1F1FA}\u{1F1F8}', formatting: 'prefix' },
  EUR: { name: 'Euro', symbol: '\u20AC', flag: '\u{1F1EA}\u{1F1FA}', formatting: 'prefix' },
  GBP: { name: 'British Pound', symbol: '\u00A3', flag: '\u{1F1EC}\u{1F1E7}', formatting: 'prefix' },
  SAR: { name: 'Saudi Riyal', symbol: 'SAR', flag: '\u{1F1F8}\u{1F1E6}', formatting: 'standard' },
  QAR: { name: 'Qatari Riyal', symbol: 'QAR', flag: '\u{1F1F6}\u{1F1E6}', formatting: 'standard' },
  AUD: { name: 'Australian Dollar', symbol: 'A$', flag: '\u{1F1E6}\u{1F1FA}', formatting: 'prefix' },
};

// ── Role Levels (simplified — salaries & overheads now live on CountryProfile) ──
export const roleDefaults: Record<RoleLevelId, RoleLevel> = {
  junior: {
    name: 'Junior-Level',
    subtitle: 'Admin, Support Staff',
    gradient: 'from-green-400 to-emerald-600',
    bgColor: 'bg-green-50',
  },
  mid: {
    name: 'Mid-Level',
    subtitle: 'Accountant, HR Executive',
    gradient: 'from-blue-400 to-indigo-700',
    bgColor: 'bg-blue-50',
  },
  senior: {
    name: 'Senior-Level',
    subtitle: 'Finance Manager, Ops Head',
    gradient: 'from-purple-400 to-pink-600',
    bgColor: 'bg-purple-50',
  },
};

// ── Team definitions (9 industry-agnostic teams) ──
export const teams: TeamDefinition[] = [
  {
    id: 'sales',
    name: 'Sales & Business Dev',
    iconName: 'DollarSign',
    description: 'Lead gen, pipeline, proposals',
    gradient: 'from-green-400 to-emerald-600',
    bgColor: 'bg-green-50',
    borderColor: 'border-green-500',
    bsgServices: ['Lead follow-up scheduling', 'Proposal formatting & templates', 'CRM data management', 'Meeting coordination'],
    tasks: [
      { id: 'lead_generation', name: 'Lead Generation & Prospecting', default: 25 },
      { id: 'client_meetings', name: 'Client Meetings & Presentations', default: 30 },
      { id: 'proposal_creation', name: 'Proposal Creation & Documentation', default: 20 },
      { id: 'follow_up', name: 'Follow-up & Relationship Management', default: 15 },
      { id: 'admin_sales', name: 'Administrative Tasks', default: 10 },
    ],
  },
  {
    id: 'operations',
    name: 'Operations Team',
    iconName: 'Settings',
    description: 'Application & case processing, review, decisions',
    gradient: 'from-blue-400 to-indigo-700',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-500',
    bsgServices: ['Document collection', 'Case data compilation', 'Template preparation', 'Stakeholder coordination'],
    tasks: [
      { id: 'case_assessment', name: 'Case Assessment & Analysis', default: 35 },
      { id: 'application_review', name: 'Application & Contract Review', default: 25 },
      { id: 'documentation', name: 'Documentation & Reporting', default: 20 },
      { id: 'stakeholder_communication', name: 'Stakeholder Communication', default: 10 },
      { id: 'admin_operations', name: 'Administrative Tasks', default: 10 },
    ],
  },
  {
    id: 'service_delivery',
    name: 'Service Delivery',
    iconName: 'Package',
    description: 'Request & order processing, fulfilment, resolution',
    gradient: 'from-orange-400 to-red-600',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-500',
    bsgServices: ['Request documentation', 'Customer status coordination', 'Document verification', 'Resolution paperwork'],
    tasks: [
      { id: 'request_processing', name: 'Request Processing & Review', default: 40 },
      { id: 'customer_communication', name: 'Customer Communication', default: 20 },
      { id: 'documentation_sd', name: 'Documentation & Record Keeping', default: 15 },
      { id: 'resolution', name: 'Resolution & Fulfilment', default: 15 },
      { id: 'admin_sd', name: 'Administrative Tasks', default: 10 },
    ],
  },
  {
    id: 'customer_service',
    name: 'Customer Service',
    iconName: 'Headphones',
    description: 'Inquiries, account changes, renewals, complaints',
    gradient: 'from-purple-400 to-pink-600',
    bgColor: 'bg-purple-50',
    borderColor: 'border-purple-500',
    bsgServices: ['Inquiry handling', 'Account change processing', 'Renewal coordination', 'Complaint tracking'],
    tasks: [
      { id: 'customer_inquiries', name: 'Customer Inquiries & Support', default: 40 },
      { id: 'account_changes', name: 'Account & Contract Changes', default: 20 },
      { id: 'renewals', name: 'Account Renewals & Retention', default: 15 },
      { id: 'complaint_handling', name: 'Complaint Handling', default: 15 },
      { id: 'admin_cs', name: 'Administrative Tasks', default: 10 },
    ],
  },
  {
    id: 'finance',
    name: 'Finance & Accounting',
    iconName: 'Calculator',
    description: 'Bookkeeping, reporting, billing, reconciliations',
    gradient: 'from-teal-400 to-cyan-600',
    bgColor: 'bg-teal-50',
    borderColor: 'border-teal-500',
    bsgServices: ['Invoice processing & AP/AR', 'Bookkeeping support', 'Report preparation', 'Payment follow-up'],
    tasks: [
      { id: 'accounting', name: 'Accounting & Bookkeeping', default: 30 },
      { id: 'financial_reporting', name: 'Financial Reporting', default: 20 },
      { id: 'billing_collections', name: 'Billing & Collections', default: 15 },
      { id: 'financial_analysis', name: 'Financial Analysis', default: 15 },
      { id: 'regulatory_reporting', name: 'Regulatory Reporting', default: 20 },
    ],
  },
  {
    id: 'compliance',
    name: 'Compliance & Risk',
    iconName: 'Shield',
    description: 'Regulatory monitoring, audit support, reporting',
    gradient: 'from-indigo-400 to-violet-700',
    bgColor: 'bg-indigo-50',
    borderColor: 'border-indigo-500',
    bsgServices: ['Document compilation', 'Compliance tracking', 'Audit preparation', 'Procedure updates'],
    tasks: [
      { id: 'regulatory_monitoring', name: 'Regulatory Monitoring', default: 25 },
      { id: 'compliance_reporting', name: 'Compliance Reporting', default: 25 },
      { id: 'audit_support', name: 'Audit Support', default: 20 },
      { id: 'procedure_updates', name: 'Procedure & Process Updates', default: 15 },
      { id: 'training_compliance', name: 'Training & Communication', default: 15 },
    ],
  },
  {
    id: 'it_support',
    name: 'IT Support & Helpdesk',
    iconName: 'Monitor',
    description: 'Ticket handling, system admin, user support',
    gradient: 'from-emerald-400 to-teal-600',
    bgColor: 'bg-emerald-50',
    borderColor: 'border-emerald-500',
    bsgServices: ['L1/L2 helpdesk tickets', 'User access & onboarding', 'System admin & maintenance', 'IT documentation'],
    tasks: [
      { id: 'ticket_handling', name: 'L1/L2 Ticket Handling', default: 40 },
      { id: 'system_admin', name: 'System Administration', default: 20 },
      { id: 'user_onboarding', name: 'User Onboarding & Access Management', default: 15 },
      { id: 'monitoring_reporting', name: 'Monitoring & Reporting', default: 15 },
      { id: 'it_documentation', name: 'Documentation & Admin', default: 10 },
    ],
  },
  {
    id: 'hr_ops',
    name: 'HR & People Operations',
    iconName: 'Users',
    description: 'Recruitment admin, onboarding, payroll support',
    gradient: 'from-pink-400 to-purple-700',
    bgColor: 'bg-pink-50',
    borderColor: 'border-pink-500',
    bsgServices: ['Recruitment admin & CV screening', 'Onboarding & offboarding', 'Payroll processing support', 'L&D coordination'],
    tasks: [
      { id: 'recruitment', name: 'Recruitment & Screening', default: 30 },
      { id: 'onboarding', name: 'Onboarding & Offboarding', default: 20 },
      { id: 'payroll_support', name: 'Payroll Processing Support', default: 20 },
      { id: 'ld_coordination', name: 'L&D Coordination', default: 15 },
      { id: 'hr_admin', name: 'HR Administration', default: 15 },
    ],
  },
  {
    id: 'data_backoffice',
    name: 'Data & Back Office',
    iconName: 'Database',
    description: 'Data entry, document processing, quality checks',
    gradient: 'from-amber-400 to-orange-600',
    bgColor: 'bg-amber-50',
    borderColor: 'border-amber-500',
    bsgServices: ['Data entry & validation', 'Document processing', 'Quality control', 'Reporting & compilation'],
    tasks: [
      { id: 'data_entry', name: 'Data Entry & Validation', default: 35 },
      { id: 'document_processing', name: 'Document Processing & Indexing', default: 25 },
      { id: 'quality_control', name: 'Quality Control & Checking', default: 20 },
      { id: 'reporting_compilation', name: 'Reporting & Data Compilation', default: 10 },
      { id: 'admin_filing', name: 'Admin & Filing', default: 10 },
    ],
  },
];

// ── Diagnostic questions for each team (9 sets) ──
export const teamQuestions: Record<string, TeamQuestion[]> = {
  sales: [
    { question: 'How often do follow-ups get missed or delayed?', weight: 25, options: [{ label: 'Never \u2014 Automated systems', inefficiency: 0, time_loss: 0 }, { label: 'Sometimes \u2014 Manual tracking', inefficiency: 50, time_loss: 45 }, { label: 'Often \u2014 No systematic approach', inefficiency: 100, time_loss: 90 }] },
    { question: 'Are proposals created from templates or from scratch?', weight: 20, options: [{ label: 'Always use templates', inefficiency: 0, time_loss: 0 }, { label: 'Somewhat templated', inefficiency: 50, time_loss: 30 }, { label: 'Created manually each time', inefficiency: 100, time_loss: 60 }] },
    { question: 'Is CRM data entry automated or manual?', weight: 20, options: [{ label: 'Fully automated', inefficiency: 0, time_loss: 0 }, { label: 'Mixed approach', inefficiency: 50, time_loss: 30 }, { label: 'Completely manual', inefficiency: 100, time_loss: 60 }] },
    { question: 'How often do meetings need rescheduling due to conflicts?', weight: 15, options: [{ label: 'Rarely \u2014 Good coordination', inefficiency: 0, time_loss: 0 }, { label: 'Sometimes \u2014 Manual scheduling', inefficiency: 50, time_loss: 15 }, { label: 'Often \u2014 Poor coordination', inefficiency: 100, time_loss: 30 }] },
    { question: 'Are client communications tracked systematically?', weight: 20, options: [{ label: 'Always tracked automatically', inefficiency: 0, time_loss: 0 }, { label: 'Mixed tracking', inefficiency: 50, time_loss: 30 }, { label: 'Not systematically tracked', inefficiency: 100, time_loss: 60 }] },
  ],
  operations: [
    { question: 'How often do case reviews get delayed due to missing information?', weight: 25, options: [{ label: 'Never \u2014 Complete data upfront', inefficiency: 0, time_loss: 0 }, { label: 'Sometimes \u2014 Minor delays', inefficiency: 50, time_loss: 45 }, { label: 'Often \u2014 Major delays', inefficiency: 100, time_loss: 90 }] },
    { question: 'Is application or case data entry automated or manual?', weight: 20, options: [{ label: 'Fully automated systems', inefficiency: 0, time_loss: 0 }, { label: 'Partially automated', inefficiency: 50, time_loss: 30 }, { label: 'Completely manual entry', inefficiency: 100, time_loss: 60 }] },
    { question: 'How often do you re-review the same cases multiple times?', weight: 20, options: [{ label: 'Never \u2014 Clear guidelines', inefficiency: 0, time_loss: 0 }, { label: 'Sometimes \u2014 Unclear cases', inefficiency: 50, time_loss: 30 }, { label: 'Often \u2014 No clear standards', inefficiency: 100, time_loss: 60 }] },
    { question: 'Are case notes and decisions clearly documented?', weight: 15, options: [{ label: 'Always \u2014 Standardised format', inefficiency: 0, time_loss: 0 }, { label: 'Usually \u2014 Some gaps', inefficiency: 50, time_loss: 15 }, { label: 'Poorly documented', inefficiency: 100, time_loss: 30 }] },
    { question: 'How smooth are handoffs between operations and other teams?', weight: 20, options: [{ label: 'Seamless \u2014 Clear process', inefficiency: 0, time_loss: 0 }, { label: 'Some friction', inefficiency: 50, time_loss: 30 }, { label: 'Frequent miscommunication', inefficiency: 100, time_loss: 60 }] },
  ],
  service_delivery: [
    { question: 'How often do required documents go missing or get delayed?', weight: 25, options: [{ label: 'Never \u2014 Digital tracking', inefficiency: 0, time_loss: 0 }, { label: 'Sometimes \u2014 Manual tracking', inefficiency: 50, time_loss: 45 }, { label: 'Often \u2014 Poor documentation', inefficiency: 100, time_loss: 90 }] },
    { question: 'Are request or ticket status updates automated or manual?', weight: 20, options: [{ label: 'Fully automated', inefficiency: 0, time_loss: 0 }, { label: 'Partially automated', inefficiency: 50, time_loss: 30 }, { label: 'Completely manual', inefficiency: 100, time_loss: 60 }] },
    { question: 'How often do customers chase you for status updates?', weight: 15, options: [{ label: 'Rarely \u2014 Proactive updates sent', inefficiency: 0, time_loss: 0 }, { label: 'Sometimes', inefficiency: 50, time_loss: 20 }, { label: 'Very often \u2014 Poor communication', inefficiency: 100, time_loss: 40 }] },
    { question: 'Is document verification done manually or automated?', weight: 20, options: [{ label: 'Automated verification', inefficiency: 0, time_loss: 0 }, { label: 'Semi-automated', inefficiency: 50, time_loss: 30 }, { label: 'Completely manual', inefficiency: 100, time_loss: 60 }] },
    { question: 'How often do requests get delayed due to missing information?', weight: 20, options: [{ label: 'Rarely \u2014 Complete submissions', inefficiency: 0, time_loss: 0 }, { label: 'Sometimes', inefficiency: 50, time_loss: 30 }, { label: 'Frequently \u2014 Poor initial review', inefficiency: 100, time_loss: 60 }] },
  ],
  customer_service: [
    { question: 'How quickly do you respond to customer inquiries?', weight: 25, options: [{ label: 'Immediately \u2014 Automated responses', inefficiency: 0, time_loss: 0 }, { label: 'Within hours \u2014 Manual tracking', inefficiency: 50, time_loss: 45 }, { label: 'Days \u2014 No systematic approach', inefficiency: 100, time_loss: 90 }] },
    { question: 'Is complaint tracking automated or manual?', weight: 20, options: [{ label: 'Fully automated system', inefficiency: 0, time_loss: 0 }, { label: 'Partially tracked', inefficiency: 50, time_loss: 30 }, { label: 'Manual spreadsheets', inefficiency: 100, time_loss: 60 }] },
    { question: 'How are account or contract changes processed?', weight: 20, options: [{ label: 'Automated workflow', inefficiency: 0, time_loss: 0 }, { label: 'Semi-automated', inefficiency: 50, time_loss: 30 }, { label: 'Completely manual', inefficiency: 100, time_loss: 60 }] },
    { question: 'How often do customers repeat the same information to different agents?', weight: 15, options: [{ label: 'Never \u2014 Shared system', inefficiency: 0, time_loss: 0 }, { label: 'Sometimes', inefficiency: 50, time_loss: 15 }, { label: 'Often \u2014 No information sharing', inefficiency: 100, time_loss: 30 }] },
    { question: 'Are customer interactions logged systematically?', weight: 20, options: [{ label: 'Always \u2014 Automated logging', inefficiency: 0, time_loss: 0 }, { label: 'Usually \u2014 Manual notes', inefficiency: 50, time_loss: 30 }, { label: 'Inconsistent logging', inefficiency: 100, time_loss: 60 }] },
  ],
  finance: [
    { question: 'How often do account reconciliations require manual intervention?', weight: 25, options: [{ label: 'Never \u2014 Fully automated', inefficiency: 0, time_loss: 0 }, { label: 'Sometimes \u2014 Semi-automated', inefficiency: 50, time_loss: 45 }, { label: 'Often \u2014 Mostly manual', inefficiency: 100, time_loss: 90 }] },
    { question: 'Are financial reports generated automatically or manually?', weight: 20, options: [{ label: 'Fully automated', inefficiency: 0, time_loss: 0 }, { label: 'Partially automated', inefficiency: 50, time_loss: 30 }, { label: 'Manual compilation', inefficiency: 100, time_loss: 60 }] },
    { question: 'How often do payment follow-ups get missed?', weight: 20, options: [{ label: 'Never \u2014 Automated reminders', inefficiency: 0, time_loss: 0 }, { label: 'Sometimes \u2014 Manual tracking', inefficiency: 50, time_loss: 30 }, { label: 'Often \u2014 No systematic follow-up', inefficiency: 100, time_loss: 60 }] },
    { question: 'How frequently do invoice errors occur?', weight: 15, options: [{ label: 'Rarely \u2014 Automated validation', inefficiency: 0, time_loss: 0 }, { label: 'Sometimes', inefficiency: 50, time_loss: 15 }, { label: 'Often \u2014 Manual processes', inefficiency: 100, time_loss: 30 }] },
    { question: 'Is expense tracking automated or manual?', weight: 20, options: [{ label: 'Fully automated', inefficiency: 0, time_loss: 0 }, { label: 'Semi-automated', inefficiency: 50, time_loss: 30 }, { label: 'Manual spreadsheets', inefficiency: 100, time_loss: 60 }] },
  ],
  compliance: [
    { question: 'How much time is spent preparing for audits?', weight: 25, options: [{ label: 'Minimal \u2014 Always audit-ready', inefficiency: 0, time_loss: 0 }, { label: 'Moderate preparation needed', inefficiency: 50, time_loss: 45 }, { label: 'Extensive preparation required', inefficiency: 100, time_loss: 90 }] },
    { question: 'Are compliance logs maintained automatically?', weight: 20, options: [{ label: 'Fully automated logging', inefficiency: 0, time_loss: 0 }, { label: 'Partially automated', inefficiency: 50, time_loss: 30 }, { label: 'Manual record keeping', inefficiency: 100, time_loss: 60 }] },
    { question: 'How often do regulatory updates get missed or delayed?', weight: 20, options: [{ label: 'Never \u2014 Automated alerts', inefficiency: 0, time_loss: 0 }, { label: 'Sometimes \u2014 Manual monitoring', inefficiency: 50, time_loss: 30 }, { label: 'Often \u2014 Poor tracking', inefficiency: 100, time_loss: 60 }] },
    { question: 'Do you experience alert fatigue from compliance systems?', weight: 15, options: [{ label: 'No \u2014 Smart filtering', inefficiency: 0, time_loss: 0 }, { label: 'Sometimes \u2014 Too many alerts', inefficiency: 50, time_loss: 15 }, { label: 'Often \u2014 Information overload', inefficiency: 100, time_loss: 30 }] },
    { question: 'Is regulatory reporting automated or manual?', weight: 20, options: [{ label: 'Fully automated', inefficiency: 0, time_loss: 0 }, { label: 'Semi-automated', inefficiency: 50, time_loss: 30 }, { label: 'Manual compilation', inefficiency: 100, time_loss: 60 }] },
  ],
  it_support: [
    { question: 'How quickly are IT support tickets resolved on average?', weight: 25, options: [{ label: 'Within SLA \u2014 Automated triage', inefficiency: 0, time_loss: 0 }, { label: 'Delays \u2014 Manual prioritisation', inefficiency: 50, time_loss: 45 }, { label: 'Often breached \u2014 No clear process', inefficiency: 100, time_loss: 90 }] },
    { question: 'Is ticket routing and triage automated or manual?', weight: 20, options: [{ label: 'Fully automated routing', inefficiency: 0, time_loss: 0 }, { label: 'Partially automated', inefficiency: 50, time_loss: 30 }, { label: 'All manual assignment', inefficiency: 100, time_loss: 60 }] },
    { question: 'How often do users contact IT with repeat or recurring issues?', weight: 20, options: [{ label: 'Rarely \u2014 Root causes resolved', inefficiency: 0, time_loss: 0 }, { label: 'Sometimes \u2014 Partial fixes', inefficiency: 50, time_loss: 30 }, { label: 'Frequently \u2014 No root cause analysis', inefficiency: 100, time_loss: 60 }] },
    { question: 'Are system access requests processed within agreed timelines?', weight: 15, options: [{ label: 'Always \u2014 Automated workflow', inefficiency: 0, time_loss: 0 }, { label: 'Usually \u2014 Manual approvals', inefficiency: 50, time_loss: 15 }, { label: 'Often delayed \u2014 No clear process', inefficiency: 100, time_loss: 30 }] },
    { question: 'Is IT documentation and knowledge base kept up to date?', weight: 20, options: [{ label: 'Always \u2014 Maintained systematically', inefficiency: 0, time_loss: 0 }, { label: 'Partially \u2014 Some gaps', inefficiency: 50, time_loss: 30 }, { label: 'Rarely updated', inefficiency: 100, time_loss: 60 }] },
  ],
  hr_ops: [
    { question: 'How much of HR time is spent on manual data entry vs. strategic work?', weight: 25, options: [{ label: 'Mostly strategic \u2014 Systems handle admin', inefficiency: 0, time_loss: 0 }, { label: 'Mixed \u2014 Some manual burden', inefficiency: 50, time_loss: 45 }, { label: 'Mostly admin \u2014 Little time for strategy', inefficiency: 100, time_loss: 90 }] },
    { question: 'Is the onboarding process standardised and documented?', weight: 20, options: [{ label: 'Fully standardised & automated', inefficiency: 0, time_loss: 0 }, { label: 'Somewhat standardised', inefficiency: 50, time_loss: 30 }, { label: 'Ad-hoc, varies by manager', inefficiency: 100, time_loss: 60 }] },
    { question: 'How often do payroll errors or late submissions occur?', weight: 20, options: [{ label: 'Rarely \u2014 Automated validation', inefficiency: 0, time_loss: 0 }, { label: 'Sometimes \u2014 Manual checks needed', inefficiency: 50, time_loss: 30 }, { label: 'Often \u2014 Mostly manual process', inefficiency: 100, time_loss: 60 }] },
    { question: 'Are job postings and CV screening handled manually?', weight: 15, options: [{ label: 'Automated \u2014 ATS handles screening', inefficiency: 0, time_loss: 0 }, { label: 'Partially automated', inefficiency: 50, time_loss: 15 }, { label: 'Fully manual \u2014 No ATS', inefficiency: 100, time_loss: 30 }] },
    { question: 'Is HR reporting compiled manually from multiple sources?', weight: 20, options: [{ label: 'Auto-generated from HRIS', inefficiency: 0, time_loss: 0 }, { label: 'Semi-automated', inefficiency: 50, time_loss: 30 }, { label: 'Manual spreadsheet compilation', inefficiency: 100, time_loss: 60 }] },
  ],
  data_backoffice: [
    { question: 'What percentage of data entry is manual vs. automated?', weight: 25, options: [{ label: 'Mostly automated \u2014 Minimal manual', inefficiency: 0, time_loss: 0 }, { label: 'Mixed \u2014 Significant manual input', inefficiency: 50, time_loss: 45 }, { label: 'Entirely manual entry', inefficiency: 100, time_loss: 90 }] },
    { question: 'How often do data errors or rework occur due to manual input?', weight: 20, options: [{ label: 'Rarely \u2014 Automated validation', inefficiency: 0, time_loss: 0 }, { label: 'Sometimes \u2014 Spot checks needed', inefficiency: 50, time_loss: 30 }, { label: 'Frequently \u2014 High error rate', inefficiency: 100, time_loss: 60 }] },
    { question: 'How long does document processing take from receipt to completion?', weight: 20, options: [{ label: 'Within SLA \u2014 Streamlined workflow', inefficiency: 0, time_loss: 0 }, { label: 'Sometimes delayed', inefficiency: 50, time_loss: 30 }, { label: 'Frequent backlogs', inefficiency: 100, time_loss: 60 }] },
    { question: 'Are quality checks done manually or through automated validation?', weight: 15, options: [{ label: 'Automated validation rules', inefficiency: 0, time_loss: 0 }, { label: 'Semi-automated with manual review', inefficiency: 50, time_loss: 15 }, { label: 'Fully manual checking', inefficiency: 100, time_loss: 30 }] },
    { question: 'Is reporting compiled manually from multiple data sources?', weight: 20, options: [{ label: 'Auto-generated dashboards', inefficiency: 0, time_loss: 0 }, { label: 'Semi-automated', inefficiency: 50, time_loss: 30 }, { label: 'Manual compilation from spreadsheets', inefficiency: 100, time_loss: 60 }] },
  ],
};

// ── Initial form state ──
export const initialFormData: FormDataState = {
  fullName: '',
  companyEmail: '',
  companyName: '',
  mobileNumber: '',
  selectedCountry: '',
  selectedCurrency: '',
  teamSize: '',
  fullSalary: '',
  costOverrides: {},
  costCustomFlags: {},
  otherCosts: '0',
  teamMaturity: '',
  diagnosticAnswers: {},
  primaryGoal: '',
  targetEfficiency: '',
  timeline: '',
};
