import type {
  CurrencyCode,
  CurrencyInfo,
  RoleLevelId,
  RoleLevel,
  TeamDefinition,
  TeamQuestion,
  FormDataState,
} from './types';

// ── Currency definitions ──
export const currencies: Record<CurrencyCode, CurrencyInfo> = {
  AED: { name: 'UAE Dirham', symbol: 'AED', flag: '\u{1F1E6}\u{1F1EA}', formatting: 'standard' },
  USD: { name: 'US Dollar', symbol: '$', flag: '\u{1F1FA}\u{1F1F8}', formatting: 'prefix' },
  EUR: { name: 'Euro', symbol: '\u20AC', flag: '\u{1F1EA}\u{1F1FA}', formatting: 'prefix' },
  GBP: { name: 'British Pound', symbol: '\u00A3', flag: '\u{1F1EC}\u{1F1E7}', formatting: 'prefix' },
  SAR: { name: 'Saudi Riyal', symbol: 'SAR', flag: '\u{1F1F8}\u{1F1E6}', formatting: 'standard' },
  QAR: { name: 'Qatari Riyal', symbol: 'QAR', flag: '\u{1F1F6}\u{1F1E6}', formatting: 'standard' },
};

// ── Role defaults with currency-specific salaries & overheads ──
export const roleDefaults: Record<RoleLevelId, RoleLevel> = {
  junior: {
    name: 'Junior-Level (Admin, Support Staff)',
    salaries: { AED: 48000, USD: 35000, EUR: 32000, GBP: 28000, SAR: 45000, QAR: 50000 },
    overheads: {
      AED: { visaCosts: 3750, insurance: 1899, training: 1500, equipment: 4000, officeSpace: 12000, annualFlight: 1500 },
      USD: { visaCosts: 1000, insurance: 2400, training: 1200, equipment: 3200, officeSpace: 9600, annualFlight: 1500 },
      EUR: { visaCosts: 900, insurance: 2200, training: 1100, equipment: 3000, officeSpace: 9000, annualFlight: 1500 },
      GBP: { visaCosts: 800, insurance: 1900, training: 1000, equipment: 2800, officeSpace: 8400, annualFlight: 1500 },
      SAR: { visaCosts: 3500, insurance: 1800, training: 1400, equipment: 3800, officeSpace: 11400, annualFlight: 1500 },
      QAR: { visaCosts: 4000, insurance: 2000, training: 1600, equipment: 4200, officeSpace: 12600, annualFlight: 1500 },
    },
    bsgRate: 0.75,
    gradient: 'from-green-400 to-emerald-600',
    bgColor: 'bg-green-50',
  },
  mid: {
    name: 'Mid-Level (Accountant, HR Executive)',
    salaries: { AED: 60000, USD: 55000, EUR: 50000, GBP: 42000, SAR: 65000, QAR: 70000 },
    overheads: {
      AED: { visaCosts: 3500, insurance: 1899, training: 2000, equipment: 4000, officeSpace: 12000, annualFlight: 1500 },
      USD: { visaCosts: 950, insurance: 2400, training: 1600, equipment: 3200, officeSpace: 9600, annualFlight: 1500 },
      EUR: { visaCosts: 850, insurance: 2200, training: 1500, equipment: 3000, officeSpace: 9000, annualFlight: 1500 },
      GBP: { visaCosts: 750, insurance: 1900, training: 1300, equipment: 2800, officeSpace: 8400, annualFlight: 1500 },
      SAR: { visaCosts: 3300, insurance: 1800, training: 1900, equipment: 3800, officeSpace: 11400, annualFlight: 1500 },
      QAR: { visaCosts: 3800, insurance: 2000, training: 2100, equipment: 4200, officeSpace: 12600, annualFlight: 1500 },
    },
    bsgRate: 0.84,
    gradient: 'from-navy-400 to-navy-700',
    bgColor: 'bg-navy-50',
  },
  senior: {
    name: 'Senior-Level (Finance Manager, Operations Head)',
    salaries: { AED: 120000, USD: 95000, EUR: 85000, GBP: 75000, SAR: 120000, QAR: 130000 },
    overheads: {
      AED: { visaCosts: 5000, insurance: 4000, training: 3000, equipment: 5000, officeSpace: 15000, annualFlight: 1500 },
      USD: { visaCosts: 1400, insurance: 3200, training: 2400, equipment: 4000, officeSpace: 12000, annualFlight: 1500 },
      EUR: { visaCosts: 1200, insurance: 2900, training: 2200, equipment: 3700, officeSpace: 11100, annualFlight: 1500 },
      GBP: { visaCosts: 1100, insurance: 2600, training: 2000, equipment: 3500, officeSpace: 10500, annualFlight: 1500 },
      SAR: { visaCosts: 4700, insurance: 3800, training: 2850, equipment: 4750, officeSpace: 14250, annualFlight: 1500 },
      QAR: { visaCosts: 5200, insurance: 4200, training: 3150, equipment: 5250, officeSpace: 15750, annualFlight: 1500 },
    },
    bsgRate: 0.80,
    gradient: 'from-gold-400 to-gold-700',
    bgColor: 'bg-gold-50',
  },
};

// ── Team definitions ──
export const teams: TeamDefinition[] = [
  {
    id: 'sales',
    name: 'Sales Team',
    iconName: 'DollarSign',
    description: 'Lead generation, client meetings, proposal creation',
    gradient: 'from-green-400 to-emerald-600',
    bgColor: 'bg-green-50',
    borderColor: 'border-green-500',
    bsgServices: ['Lead follow-up scheduling', 'Proposal formatting', 'CRM updates', 'Meeting coordination'],
    tasks: [
      { id: 'lead_generation', name: 'Lead Generation & Prospecting', default: 25 },
      { id: 'client_meetings', name: 'Client Meetings & Presentations', default: 30 },
      { id: 'proposal_creation', name: 'Proposal Creation & Documentation', default: 20 },
      { id: 'follow_up', name: 'Follow-up & Relationship Management', default: 15 },
      { id: 'admin_sales', name: 'Administrative Tasks', default: 10 },
    ],
  },
  {
    id: 'underwriting',
    name: 'Underwriting Team',
    iconName: 'Shield',
    description: 'Risk assessment, policy evaluation, decision making',
    gradient: 'from-navy-400 to-navy-700',
    bgColor: 'bg-navy-50',
    borderColor: 'border-navy-500',
    bsgServices: ['Document collection', 'Risk data compilation', 'Policy template prep', 'Stakeholder coordination'],
    tasks: [
      { id: 'risk_assessment', name: 'Risk Assessment & Analysis', default: 35 },
      { id: 'policy_review', name: 'Policy Review & Evaluation', default: 25 },
      { id: 'documentation', name: 'Documentation & Reporting', default: 20 },
      { id: 'stakeholder_communication', name: 'Stakeholder Communication', default: 10 },
      { id: 'admin_underwriting', name: 'Administrative Tasks', default: 10 },
    ],
  },
  {
    id: 'claims',
    name: 'Claims Team',
    iconName: 'FileText',
    description: 'Claims processing, investigation, settlement',
    gradient: 'from-orange-400 to-red-600',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-500',
    bsgServices: ['Claim documentation', 'Customer coordination', 'Document verification', 'Settlement paperwork'],
    tasks: [
      { id: 'claim_processing', name: 'Claim Processing & Investigation', default: 40 },
      { id: 'customer_communication', name: 'Customer Communication', default: 20 },
      { id: 'documentation_claims', name: 'Documentation & Record Keeping', default: 15 },
      { id: 'settlement_processing', name: 'Settlement Processing', default: 15 },
      { id: 'admin_claims', name: 'Administrative Tasks', default: 10 },
    ],
  },
  {
    id: 'customer_service',
    name: 'Customer Service',
    iconName: 'Headphones',
    description: 'Customer inquiries, policy changes, renewals',
    gradient: 'from-gold-400 to-gold-700',
    bgColor: 'bg-gold-50',
    borderColor: 'border-gold-500',
    bsgServices: ['Inquiry handling', 'Policy documentation', 'Renewal coordination', 'Complaint tracking'],
    tasks: [
      { id: 'customer_inquiries', name: 'Customer Inquiries & Support', default: 40 },
      { id: 'policy_changes', name: 'Policy Changes & Updates', default: 20 },
      { id: 'renewals', name: 'Policy Renewals', default: 15 },
      { id: 'complaint_handling', name: 'Complaint Handling', default: 15 },
      { id: 'admin_cs', name: 'Administrative Tasks', default: 10 },
    ],
  },
  {
    id: 'finance',
    name: 'Finance Team',
    iconName: 'Calculator',
    description: 'Accounting, reporting, billing, financial analysis',
    gradient: 'from-teal-400 to-cyan-600',
    bgColor: 'bg-teal-50',
    borderColor: 'border-teal-500',
    bsgServices: ['Invoice processing', 'Bookkeeping support', 'Report preparation', 'Payment follow-up'],
    tasks: [
      { id: 'accounting', name: 'Accounting & Bookkeeping', default: 30 },
      { id: 'financial_reporting', name: 'Financial Reporting', default: 20 },
      { id: 'billing_collections', name: 'Billing & Collections', default: 15 },
      { id: 'financial_analysis', name: 'Financial Analysis', default: 15 },
      { id: 'regulatory_reporting', name: 'Regulatory Reporting', default: 20 },
    ],
  },
  {
    id: 'compliance',
    name: 'Compliance Team',
    iconName: 'Settings',
    description: 'Regulatory reporting, risk monitoring, audit support',
    gradient: 'from-navy-400 to-navy-800',
    bgColor: 'bg-navy-50',
    borderColor: 'border-navy-500',
    bsgServices: ['Document compilation', 'Compliance tracking', 'Audit preparation', 'Policy coordination'],
    tasks: [
      { id: 'regulatory_monitoring', name: 'Regulatory Monitoring', default: 25 },
      { id: 'compliance_reporting', name: 'Compliance Reporting', default: 25 },
      { id: 'audit_support', name: 'Audit Support', default: 20 },
      { id: 'policy_updates', name: 'Policy & Procedure Updates', default: 15 },
      { id: 'training_compliance', name: 'Training & Communication', default: 15 },
    ],
  },
];

// ── Diagnostic questions for each team ──
export const teamQuestions: Record<string, TeamQuestion[]> = {
  sales: [
    { question: "How often do follow-ups get missed or delayed?", weight: 25, options: [{ label: "Never - Automated systems", inefficiency: 0, time_loss: 0 }, { label: "Sometimes - Manual tracking", inefficiency: 50, time_loss: 45 }, { label: "Often - No systematic approach", inefficiency: 100, time_loss: 90 }] },
    { question: "Are proposals created from templates or from scratch?", weight: 20, options: [{ label: "Always use templates", inefficiency: 0, time_loss: 0 }, { label: "Somewhat templated", inefficiency: 50, time_loss: 30 }, { label: "Created manually each time", inefficiency: 100, time_loss: 60 }] },
    { question: "Is CRM data entry automated or manual?", weight: 20, options: [{ label: "Fully automated", inefficiency: 0, time_loss: 0 }, { label: "Mixed approach", inefficiency: 50, time_loss: 30 }, { label: "Completely manual", inefficiency: 100, time_loss: 60 }] },
    { question: "How often do meetings need rescheduling due to conflicts?", weight: 15, options: [{ label: "Rarely - Good coordination", inefficiency: 0, time_loss: 0 }, { label: "Sometimes - Manual scheduling", inefficiency: 50, time_loss: 15 }, { label: "Often - Poor coordination", inefficiency: 100, time_loss: 30 }] },
    { question: "Are client communications tracked systematically?", weight: 20, options: [{ label: "Always tracked automatically", inefficiency: 0, time_loss: 0 }, { label: "Mixed tracking", inefficiency: 50, time_loss: 30 }, { label: "Not systematically tracked", inefficiency: 100, time_loss: 60 }] },
  ],
  underwriting: [
    { question: "How often do risk assessments get delayed due to missing information?", weight: 25, options: [{ label: "Never - Complete data upfront", inefficiency: 0, time_loss: 0 }, { label: "Sometimes - Minor delays", inefficiency: 50, time_loss: 45 }, { label: "Often - Major delays", inefficiency: 100, time_loss: 90 }] },
    { question: "Is policy data input automated or manual?", weight: 20, options: [{ label: "Fully automated systems", inefficiency: 0, time_loss: 0 }, { label: "Partially automated", inefficiency: 50, time_loss: 30 }, { label: "Completely manual entry", inefficiency: 100, time_loss: 60 }] },
    { question: "How often do you reassess the same risks multiple times?", weight: 20, options: [{ label: "Never - Clear guidelines", inefficiency: 0, time_loss: 0 }, { label: "Sometimes - Unclear cases", inefficiency: 50, time_loss: 30 }, { label: "Often - No clear standards", inefficiency: 100, time_loss: 60 }] },
    { question: "Are policy notes and decisions clearly documented?", weight: 15, options: [{ label: "Always - Standardized format", inefficiency: 0, time_loss: 0 }, { label: "Usually - Some gaps", inefficiency: 50, time_loss: 15 }, { label: "Poorly documented", inefficiency: 100, time_loss: 30 }] },
    { question: "How smooth are handoffs between underwriting and other teams?", weight: 20, options: [{ label: "Seamless - Clear process", inefficiency: 0, time_loss: 0 }, { label: "Some friction", inefficiency: 50, time_loss: 30 }, { label: "Frequent miscommunication", inefficiency: 100, time_loss: 60 }] },
  ],
  claims: [
    { question: "How often do required documents go missing or get delayed?", weight: 25, options: [{ label: "Never - Digital tracking", inefficiency: 0, time_loss: 0 }, { label: "Sometimes - Manual tracking", inefficiency: 50, time_loss: 45 }, { label: "Often - Poor documentation", inefficiency: 100, time_loss: 90 }] },
    { question: "Are claim status updates automated or manual?", weight: 20, options: [{ label: "Fully automated", inefficiency: 0, time_loss: 0 }, { label: "Partially automated", inefficiency: 50, time_loss: 30 }, { label: "Completely manual", inefficiency: 100, time_loss: 60 }] },
    { question: "How often do customers call asking for claim updates?", weight: 15, options: [{ label: "Rarely - Proactive updates", inefficiency: 0, time_loss: 0 }, { label: "Sometimes", inefficiency: 50, time_loss: 20 }, { label: "Very often - Poor communication", inefficiency: 100, time_loss: 40 }] },
    { question: "Is document verification done manually or automated?", weight: 20, options: [{ label: "Automated verification", inefficiency: 0, time_loss: 0 }, { label: "Semi-automated", inefficiency: 50, time_loss: 30 }, { label: "Completely manual", inefficiency: 100, time_loss: 60 }] },
    { question: "How often do claims get delayed due to missing information?", weight: 20, options: [{ label: "Rarely - Complete submissions", inefficiency: 0, time_loss: 0 }, { label: "Sometimes", inefficiency: 50, time_loss: 30 }, { label: "Frequently - Poor initial review", inefficiency: 100, time_loss: 60 }] },
  ],
  customer_service: [
    { question: "How quickly do you respond to customer inquiries?", weight: 25, options: [{ label: "Immediately - Automated responses", inefficiency: 0, time_loss: 0 }, { label: "Within hours - Manual tracking", inefficiency: 50, time_loss: 45 }, { label: "Days - No systematic approach", inefficiency: 100, time_loss: 90 }] },
    { question: "Is complaint tracking automated or manual?", weight: 20, options: [{ label: "Fully automated system", inefficiency: 0, time_loss: 0 }, { label: "Partially tracked", inefficiency: 50, time_loss: 30 }, { label: "Manual spreadsheets", inefficiency: 100, time_loss: 60 }] },
    { question: "How are policy changes processed?", weight: 20, options: [{ label: "Automated workflow", inefficiency: 0, time_loss: 0 }, { label: "Semi-automated", inefficiency: 50, time_loss: 30 }, { label: "Completely manual", inefficiency: 100, time_loss: 60 }] },
    { question: "How often do customers repeat the same information to different agents?", weight: 15, options: [{ label: "Never - Shared system", inefficiency: 0, time_loss: 0 }, { label: "Sometimes", inefficiency: 50, time_loss: 15 }, { label: "Often - No information sharing", inefficiency: 100, time_loss: 30 }] },
    { question: "Are customer interactions logged systematically?", weight: 20, options: [{ label: "Always - Automated logging", inefficiency: 0, time_loss: 0 }, { label: "Usually - Manual notes", inefficiency: 50, time_loss: 30 }, { label: "Inconsistent logging", inefficiency: 100, time_loss: 60 }] },
  ],
  finance: [
    { question: "How often do account reconciliations require manual intervention?", weight: 25, options: [{ label: "Never - Fully automated", inefficiency: 0, time_loss: 0 }, { label: "Sometimes - Semi-automated", inefficiency: 50, time_loss: 45 }, { label: "Often - Mostly manual", inefficiency: 100, time_loss: 90 }] },
    { question: "Are financial reports generated automatically or manually?", weight: 20, options: [{ label: "Fully automated", inefficiency: 0, time_loss: 0 }, { label: "Partially automated", inefficiency: 50, time_loss: 30 }, { label: "Manual compilation", inefficiency: 100, time_loss: 60 }] },
    { question: "How often do payment follow-ups get missed?", weight: 20, options: [{ label: "Never - Automated reminders", inefficiency: 0, time_loss: 0 }, { label: "Sometimes - Manual tracking", inefficiency: 50, time_loss: 30 }, { label: "Often - No systematic follow-up", inefficiency: 100, time_loss: 60 }] },
    { question: "How frequently do invoice errors occur?", weight: 15, options: [{ label: "Rarely - Automated validation", inefficiency: 0, time_loss: 0 }, { label: "Sometimes", inefficiency: 50, time_loss: 15 }, { label: "Often - Manual processes", inefficiency: 100, time_loss: 30 }] },
    { question: "Is expense tracking automated or manual?", weight: 20, options: [{ label: "Fully automated", inefficiency: 0, time_loss: 0 }, { label: "Semi-automated", inefficiency: 50, time_loss: 30 }, { label: "Manual spreadsheets", inefficiency: 100, time_loss: 60 }] },
  ],
  compliance: [
    { question: "How much time is spent preparing for audits?", weight: 25, options: [{ label: "Minimal - Always audit-ready", inefficiency: 0, time_loss: 0 }, { label: "Moderate preparation needed", inefficiency: 50, time_loss: 45 }, { label: "Extensive preparation required", inefficiency: 100, time_loss: 90 }] },
    { question: "Are compliance logs maintained automatically?", weight: 20, options: [{ label: "Fully automated logging", inefficiency: 0, time_loss: 0 }, { label: "Partially automated", inefficiency: 50, time_loss: 30 }, { label: "Manual record keeping", inefficiency: 100, time_loss: 60 }] },
    { question: "How often do policy updates get missed or delayed?", weight: 20, options: [{ label: "Never - Automated alerts", inefficiency: 0, time_loss: 0 }, { label: "Sometimes - Manual monitoring", inefficiency: 50, time_loss: 30 }, { label: "Often - Poor tracking", inefficiency: 100, time_loss: 60 }] },
    { question: "Do you experience alert fatigue from compliance systems?", weight: 15, options: [{ label: "No - Smart filtering", inefficiency: 0, time_loss: 0 }, { label: "Sometimes - Too many alerts", inefficiency: 50, time_loss: 15 }, { label: "Often - Information overload", inefficiency: 100, time_loss: 30 }] },
    { question: "Is regulatory reporting automated or manual?", weight: 20, options: [{ label: "Fully automated", inefficiency: 0, time_loss: 0 }, { label: "Semi-automated", inefficiency: 50, time_loss: 30 }, { label: "Manual compilation", inefficiency: 100, time_loss: 60 }] },
  ],
};

// ── Initial form state ──
export const initialFormData: FormDataState = {
  selectedCurrency: 'AED',
  fullName: '',
  companyEmail: '',
  companyName: '',
  mobileNumber: '',
  teamSize: '',
  fullSalary: '',
  visaCosts: '',
  visaCostsCustom: false,
  insurance: '',
  insuranceCustom: false,
  training: '',
  trainingCustom: false,
  equipment: '',
  equipmentCustom: false,
  officeSpace: '',
  officeSpaceCustom: false,
  leaveSalary: '',
  leaveSalaryCustom: false,
  annualFlight: '',
  annualFlightCustom: false,
  eosGratuity: '',
  eosGratuityCustom: false,
  otherCosts: '0',
  teamMaturity: '',
  diagnosticAnswers: {},
  primaryGoal: '',
  targetEfficiency: '',
  timeline: '',
};
